<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\FiscalData.Domain\FiscalData.Domain.csproj" />
    <ProjectReference Include="..\FiscalData.Proxy\FiscalData.Proxy.csproj" />
  </ItemGroup>

</Project>
