<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Domain\Common.Domain.csproj" />
    <ProjectReference Include="..\Treatment.Domain\Treatment.Domain.csproj" />
    <ProjectReference Include="..\Treatment.Proxy\Treatment.Proxy.csproj" />
  </ItemGroup>

</Project>
